//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubSonic.Core.VisualStudio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SubSonicCoreErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SubSonicCoreErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubSonic.Core.VisualStudio.SubSonicCoreErrors", typeof(SubSonicCoreErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugging multiple templates is not allowed..
        /// </summary>
        internal static string CannotDebugMultipleTemplates {
            get {
                return ResourceManager.GetString("CannotDebugMultipleTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DebugErrorOutput.
        /// </summary>
        internal static string DebugErrorOutput {
            get {
                return ResourceManager.GetString("DebugErrorOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error attaching to run factory process..
        /// </summary>
        internal static string ErrorAttachingToRunFactoryProcess {
            get {
                return ResourceManager.GetString("ErrorAttachingToRunFactoryProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error starting run factory process..
        /// </summary>
        internal static string ErrorStartingRunFactoryProcess {
            get {
                return ResourceManager.GetString("ErrorStartingRunFactoryProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Attaching To Process Factory: {0}.
        /// </summary>
        internal static string ExceptionAttachingToRunFactoryProcess {
            get {
                return ResourceManager.GetString("ExceptionAttachingToRunFactoryProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Starting Transformation: {0}.
        /// </summary>
        internal static string ExceptionStartingRunFactoryProcess {
            get {
                return ResourceManager.GetString("ExceptionStartingRunFactoryProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate the file specified..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was not found in the connection manager..
        /// </summary>
        internal static string MissingConnectionKey {
            get {
                return ResourceManager.GetString("MissingConnectionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register ipc channel: {0}.
        /// </summary>
        internal static string RegisterIpcChannelFailed {
            get {
                return ResourceManager.GetString("RegisterIpcChannelFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Templating Service is Unavailable.
        /// </summary>
        internal static string TextTemplatingUnavailable {
            get {
                return ResourceManager.GetString("TextTemplatingUnavailable", resourceCulture);
            }
        }
    }
}
